on:
  push:

name: create-debian-package

jobs:
  create-debian-package:
    runs-on: ubuntu-latest
    container: rust:1.90.0-trixie
    steps:
      - name: Install required packages
        run: apt-get update && apt-get install -y build-essential devscripts bash-completion pkg-config rsync libssl-dev

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build package
        run: ./build_deb.sh
